-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 22:34:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `organizacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organizacoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `organizacoes` (
  `id_organizacao` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `numero_endereco` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf_endereco` VARCHAR(2) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  PRIMARY KEY (`id_organizacao`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `organizacoes` (`id_organizacao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `publicacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicacoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `publicacoes` (
  `id_publicacao` INT NOT NULL,
  `tipo_publicacao` INT NOT NULL COMMENT '0 = procurase\n1 = encontrado\n2 = doacao',
  `data_criacao` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_organizacao` INT NULL,
  `tipo_pet` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `numero_endereco` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf_endereco` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_publicacao`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idpublicacoes_UNIQUE` ON `publicacoes` (`id_publicacao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(250) NOT NULL,
  `numero_endereco` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf_endereco` VARCHAR(2) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `usuarios` (`id_usuario` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios_organizacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios_organizacoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios_organizacoes` (
  `id_usuarios_organizacoes` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_organizacao` INT NOT NULL,
  PRIMARY KEY (`id_usuarios_organizacoes`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_usuarios_organizacoes_UNIQUE` ON `usuarios_organizacoes` (`id_usuarios_organizacoes` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
