insert into cadastro_raca values
(1,'Perça'),
(2,'Brithis Shorthair'),
(3,'Sphynx'),
(4,'Siamês'),
(5,'Angorá'),
(6,'Maine Coon'),
(7,'Himalaio'),
(8,'Bengal'),
(9,'Ragdoll'),
(10,'Munchkin'),
(11,'Scottish Fold'),
(12,'Abissínio'),
(13,'Birmanês'),
(14,'SRD'),
(15,'SRD'),
(16,'Pug'),
(17,'Maltês'),
(18,'Shih Tzu'),
(19,'Buldogue'),
(20,'Pit Bull'),
(21,'Spitz Alemão'),
(22,'Dachshund'),
(23,'Pastor Alemão'),
(24,'Basset'),
(25,'Schnauzer'),
(26,'Poodle'),
(27,'Rottweiler'),
(28,'Labrador'),
(29,'Pinscher'),
(30,'Lasha Apso'),
(31,'Golden Retriever'),
(32,'Yorkshire'),
(33,'Border Collie'),
(34,'Beagle'),
(35,'Boxer'),
(36,'Chihuahua'),
(37,'Cocker'),
(38,'Chow Chow'),
(39,'Corgi'),
(40,'Buldogue Francês'),
(41,'Buldogue Inglês'),
(42,'Bull Terrier'),
(43,'Dog de Bordeaux'),
(44,'Husky Siberiano'),
(45,'Fox Paulistinha'),
(46,'Dogo Argentino'),
(47,'Pequinês'),
(48,'Poodle Toy'),
(49,'Dalmata'),
(50,'São Bernardo'),
(51,'Whippet');

insert into cadastro_cor values
(1,'Preto'),
(2,'Branco'),
(3,'Amarelo'),
(4,'Laranja'),
(5,'Marrom'),
(6,'Cinza'),
(7,'Cinza Azul'),
(8,'Bege'),
(9,'Malhado Branco e Preto'),
(10,'Malhado Branco e Laranja'),
(11,'Malhado Branco e Amarelo'),
(12,'Malhado Branco e Cinza'),
(13,'Malhado Branco e Cinza Azul'),
(14,'Malhado Branco e Marrom'),
(15,'Malhado Branco e Bege'),
(16,'Malhado Bege e Marrom'),
(17,'Malhado Preto e Amarelo'),
(18,'Malhado Amarelo e Laranja'),
(19,'Malhado Marrom e Preto'),
(20,'Malhado Bege e Preto'),
(21,'Malhado três cores ou mais'),
(22,'Outra');

insert into cadastro_tamanho values
(1,'Pequeno porte'),
(2,'Médio porte'),
(3,'Grande porte');
